### PR TITLE
bump Swoole to v5.0.0

### PR DESCRIPTION
**Pull request by kingIZZZY**
As advised here https://github.com/cachewerk/heroku-php-extensions/pull/19#issuecomment-1211036659 (i hope..)

### CODE REVIEW

**Comment by kingIZZZY** [comment]
Not sure I understand what's wrong and how can I fix it 🤔 any enlightenment would be appreciated

**Comment by tillkruss** [comment]
Aha. Your workflow runs don't have access to the secrets. 

I'd say get Swoole 5.0 to compile locally and then push your changes here.

**Comment by kingIZZZY** [comment]
OK will try to build swoole 5.0.0 now

Is there something I missed so that the pull request would have access to those secrets? It sounds strange that it would depend on me being able to build the extension locally... but what do I know 🤷‍♂️

**Comment by kingIZZZY** [comment]
> get Swoole 5.0 to compile locally and then push your changes here.

OK I cloned swoole/swoole-src 5.0.0 project and I think I got it to compile/build locally, what exactly am I supposed to push changes about it here in **this** project?

**Comment by tillkruss** [comment]
@kingIZZZY: See #23.

**Comment by kingIZZZY** [comment]
See my [comments](https://github.com/cachewerk/heroku-php-extensions/pull/23#issuecomment-1211493968) there and the latest commit here https://github.com/cachewerk/heroku-php-extensions/pull/22/commits/4f321af739520e5385fa5e4c535385c67fa52fd9

**Comment by tillkruss** [comment]
Closing for #30.

**Pull request closed without merging**
